# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./ShipperAPI
    
jobs:
   build:
    runs-on: [ 'Linux', 'X64', 'self-hosted']
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn compile 
        
   test:
    needs: build
    runs-on: [ 'Linux', 'X64', 'self-hosted']
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: testing
      run: mvn packgage
  
   deploy:
    needs: [build,test]
    runs-on: [ 'Linux', 'X64', 'self-hosted']
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: testing
      run: cd ~/actions-runner/deploy/shipperApi/shipperApi/ShipperAPI
    - run: sudo docker container stop postgres-containe||true
    - run: sudo docker container stop shippert2||true
    - run: sudo docker image rm ship||true
    - run: sudo docker build -t ship .
    - run: sudo docker start postgres-containe||sudo docker run --name postgres-containe -e POSTGRES_PASSWORD=postgres -d postgres:alpine
    - run: sudo docker run --name shippert2 -p 8080:8080 --link postgres-containe:postgres ship |echo "success"
