# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./ShipperAPI
    
jobs:
  build:
    runs-on: ['self-hosted', 'Linux', 'X64', 'main']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  test:
    runs-on: ['self-hosted', 'Linux', 'X64', 'main']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: testing with maven    
      run: mvn test 
  
  deploy:
    runs-on: ['self-hosted', 'Linux', 'X64', 'main']

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Build with Maven
      
      
    - run: cd ~/actions-runner/deploy/shipperApi/shipperApi/ShipperAPI
    - run: sudo docker container stop postgres-container||true
    - run: sudo docker container stop shippert2||true
    - run: sudo docker image rm ship||true
    - run: sudo docker build -t ship .
    - run: sudo docker start postgres-container||sudo docker run --name postgres-container -p 5432:5432 -e PASSWORD=postgres -d postgres
    - run: sudo docker run --name shippert2 -p 8080:8080 -link postgres-container:postgres ship |echo "success"
